# Generated by Django 2.2.7 on 2021-05-06 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rc_common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commonconfigurations',
            options={'permissions': [('system_reset_permissions', 'System Reset Permissions'), ('developer_permissions', 'Developer Permissions')]},
        ),
    ]
